### ISSUE TITLE
Create setup scripts

### ISSUE THREAD

**Issue by aadamk** [d3b-center/d3b_cbtn_summit#1]
For each module: 
1. create 00-setup.R script that installs the necessary packages for each module. 
2. include 00-setup.R as the first step in each module run script. 

A couple of bioc packages to note:
clusterProfiler
DGCA

An additional package that seemed necessary but wasn't explicitly loaded was `broom.helpers`. 

Date needed: 09/30

**Comment by komalsrathi** [comment]
Will work on this today. Thanks.

**Comment by komalsrathi** [comment]
I have added the module specific R scripts and updated corresponding bash scripts. 

1. `DGCA` doesn't seem to be called anywhere - could you point the scripts where it is needed?
2. Can you also inform where `broom.helpers` was necessary? Doesn't seem like it was an issue for me.

**Comment by komalsrathi** [comment]
Closing as the changes were committed to the master branch.
